use std::fmt;

use axum::extract::State;
use axum_extra::extract::Query;
use chrono::{DateTime, NaiveDateTime, Utc};
use defguard_common::db::Id;
use ipnetwork::IpNetwork;
use sqlx::{FromRow, Postgres, QueryBuilder, Type};
use utoipa::ToSchema;

use super::{ApiErrorResponse, pagination::{PaginatedApiResponse, PaginatedApiResult, PaginationParams}};
use crate::{appstate::AppState, auth::SessionInfo, db::models::activity_log::ActivityLogModule};

#[derive(Debug, Deserialize, Default)]
pub struct FilterParams { pub from: Option<DateTime<Utc>>, pub until: Option<DateTime<Utc>>, #[serde(default = "default_username")] pub username: Vec<String>, #[serde(default = "default_location")] pub location: Vec<String>, #[serde(default = "default_event")] pub event: Vec<String>, #[serde(default = "default_module")] pub module: Vec<ActivityLogModule>, pub search: Option<String> }
fn default_username() -> Vec<String> { Vec::new() } fn default_location() -> Vec<String> { Vec::new() } fn default_event() -> Vec<String> { Vec::new() } fn default_module() -> Vec<ActivityLogModule> { Vec::new() }
#[derive(Debug, Deserialize)] #[serde(rename_all = "lowercase")] pub struct SortParams { #[serde(default)] pub sort_by: SortKey, #[serde(default)] pub sort_order: SortOrder }
#[derive(Debug, Deserialize, Type, Serialize, Default)] #[serde(rename_all = "lowercase")] pub enum SortKey { #[default] Timestamp, Username, Location, Ip, Event, Module, Device }
impl fmt::Display for SortKey { fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result { f.write_str(match self { Self::Timestamp => "timestamp", Self::Username => "username", Self::Location => "location", Self::Ip => "ip", Self::Event => "event", Self::Module => "module::text", Self::Device => "device" }) } }
#[derive(Debug, Deserialize, Serialize, Default, Type)] #[serde(rename_all = "lowercase")] pub enum SortOrder { Asc, #[default] Desc }
impl fmt::Display for SortOrder { fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result { f.write_str(match self { Self::Asc => "ASC", Self::Desc => "DESC" }) } }

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, ToSchema)] #[serde(rename_all = "lowercase")] pub enum SiemSeverity { Critical, High, Medium, #[default] Low }
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, ToSchema)] #[serde(rename_all = "kebab-case")] pub enum SiemDetectionRuleId { AuthenticationFailures, CredentialSecurityChanges, PostureFailures, InfrastructureChanges }

#[derive(Serialize, FromRow, ToSchema)]
pub struct ApiActivityLogEvent { pub id: Id, pub timestamp: NaiveDateTime, pub user_id: Option<Id>, pub username: String, pub location: Option<String>, #[schema(value_type = Option<String>)] pub ip: Option<IpNetwork>, pub event: String, pub module: ActivityLogModule, pub device: String, pub description: Option<String>, #[sqlx(skip)] pub siem_severity: SiemSeverity, #[sqlx(skip)] pub siem_detections: Vec<SiemDetectionRuleId> }
impl ApiActivityLogEvent { fn apply_siem_classification(&mut self) { let (severity, detections) = classify_siem_event(&self.event); self.siem_severity = severity; self.siem_detections = detections; } }
fn classify_siem_event(event: &str) -> (SiemSeverity, Vec<SiemDetectionRuleId>) { let severity = match event { "recovery_code_used"|"mfa_disabled"|"user_mfa_disabled"|"gateway_deleted"|"proxy_deleted" => SiemSeverity::Critical, "user_login_failed"|"user_mfa_login_failed"|"vpn_client_mfa_failed"|"device_posture_check_failed"|"password_changed_by_admin"|"password_reset"|"user_removed"|"device_removed"|"network_device_removed" => SiemSeverity::High, "settings_updated"|"settings_updated_partial"|"enterprise_settings_updated"|"api_token_added"|"authentication_key_added"|"group_modified"|"user_groups_modified"|"gateway_disconnected"|"proxy_disconnected" => SiemSeverity::Medium, _ => SiemSeverity::Low }; let mut detections=Vec::new(); if matches!(event,"user_login_failed"|"user_mfa_login_failed"|"vpn_client_mfa_failed"){detections.push(SiemDetectionRuleId::AuthenticationFailures);} if matches!(event,"recovery_code_used"|"mfa_disabled"|"user_mfa_disabled"|"password_changed_by_admin"|"password_reset"|"api_token_added"|"authentication_key_added"){detections.push(SiemDetectionRuleId::CredentialSecurityChanges);} if event=="device_posture_check_failed"{detections.push(SiemDetectionRuleId::PostureFailures);} if matches!(event,"gateway_deleted"|"proxy_deleted"|"gateway_disconnected"|"proxy_disconnected"|"settings_updated"|"settings_updated_partial"|"enterprise_settings_updated"){detections.push(SiemDetectionRuleId::InfrastructureChanges);} (severity,detections) }

#[utoipa::path(get,path="/api/v1/activity_log",tag="activity log",params(("page"=Option<u32>,Query),("per_page"=Option<u32>,Query),("from"=Option<String>,Query),("until"=Option<String>,Query),("username"=Option<String>,Query),("event"=Option<String>,Query),("module"=Option<String>,Query),("search"=Option<String>,Query),("sort_by"=Option<String>,Query),("sort_order"=Option<String>,Query)),responses((status=200,body=PaginatedApiResponse<ApiActivityLogEvent>),(status=401,body=ApiErrorResponse),(status=500,body=ApiErrorResponse)),security(("cookie"=[]),("api_token"=[])))]
pub async fn get_activity_log_events(session_info: SessionInfo, State(appstate): State<AppState>, pagination: Query<PaginationParams>, filters: Query<FilterParams>, sorting: Query<SortParams>) -> PaginatedApiResult<ApiActivityLogEvent> { let pagination=pagination.0; let mut qb:QueryBuilder<Postgres>=QueryBuilder::new("SELECT id, timestamp, user_id, username, location, ip, event, module, device, description FROM activity_log_event WHERE 1=1 "); if !session_info.is_admin { qb.push(" AND username = ").push_bind(session_info.user.username).push(" "); } apply_filters(&mut qb,&filters); apply_sorting(&mut qb,&sorting); qb.push(" LIMIT ").push_bind(i64::from(pagination.per_page())).push(" OFFSET ").push_bind(i64::from(pagination.offset())); let mut events=qb.build_query_as::<ApiActivityLogEvent>().fetch_all(&appstate.pool).await?; for event in &mut events { event.apply_siem_classification(); } let mut count:QueryBuilder<Postgres>=QueryBuilder::new("SELECT COUNT(*) FROM activity_log_event WHERE 1=1 "); apply_filters(&mut count,&filters); let total:i64=count.build_query_scalar().fetch_one(&appstate.pool).await?; Ok(PaginatedApiResponse::new(events,pagination,total as u32)) }
fn apply_filters(q:&mut QueryBuilder<Postgres>,f:&FilterParams){ if let Some(v)=f.from{q.push(" AND timestamp >= ").push_bind(v.naive_utc());} if let Some(v)=f.until{q.push(" AND timestamp <= ").push_bind(v.naive_utc());} if !f.username.is_empty(){q.push(" AND username = ANY(").push_bind(f.username.clone()).push(") ");} if !f.location.is_empty(){q.push(" AND location = ANY(").push_bind(f.location.clone()).push(") ");} if !f.event.is_empty(){q.push(" AND event = ANY(").push_bind(f.event.clone()).push(") ");} if !f.module.is_empty(){q.push(" AND module = ANY(").push_bind(f.module.clone()).push(") ");} if let Some(s)=&f.search{q.push(" AND CONCAT(username, ' ', location, ' ', module, ' ', event, ' ', device, ' ', description, ' ') ILIKE ").push_bind(format!("%{s}%")).push(" ");} }
fn apply_sorting(q:&mut QueryBuilder<Postgres>,s:&SortParams){q.push(" ORDER BY ").push(s.sort_by.to_string()).push(" ").push(s.sort_order.to_string()).push(", id ").push(s.sort_order.to_string());}

#[cfg(test)] mod tests { use super::{classify_siem_event,SiemDetectionRuleId,SiemSeverity}; #[test] fn critical(){let(s,d)=classify_siem_event("mfa_disabled");assert_eq!(s,SiemSeverity::Critical);assert_eq!(d,vec![SiemDetectionRuleId::CredentialSecurityChanges]);} #[test] fn auth_failure(){let(s,d)=classify_siem_event("user_login_failed");assert_eq!(s,SiemSeverity::High);assert_eq!(d,vec![SiemDetectionRuleId::AuthenticationFailures]);} }
